# Generated by Django 4.2.3 on 2023-08-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_city_alter_item_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.CharField(choices=[('City1', 'Maseru'), ('City2', 'Berea'), ('City3', 'Hlotse')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_sold',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(),
        ),
    ]
