# Generated by Django 4.2.3 on 2023-08-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_city_alter_item_is_sold_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.IntegerField(default='0', max_length=20),
        ),
    ]
