# Generated by Django 4.2.3 on 2023-08-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_is_verified_item_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='phone',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
