# Generated by Django 4.2.3 on 2023-08-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_alter_item_phone_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.CharField(choices=[('Maseru', 'Maseru'), ('Berea', 'Berea'), ('Hlotse', 'Hlotse')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='phone',
            field=models.IntegerField(default='00266'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DateField(blank=True, null=True),
        ),
    ]
