# Generated by Django 4.2.3 on 2023-09-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_item_city_alter_item_phone_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='verified_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
